import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BOARD)

GPIO.setup(10, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(18, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)
GPIO.setup(26, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)
GPIO.setup(21, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
GPIO.setup(15, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(7, GPIO.OUT)
GPIO.setup(5, GPIO.OUT)
def rgb(no_of_times,speed):
    for i in range(0,no_of_times):
         print "\nLed Blink = " + str(i+1)
         GPIO.output(10, True)
         GPIO.output(18, True)
         GPIO.output(26, True)
         GPIO.output(19, True)
         GPIO.output(11, True)
         time.sleep(speed)
         GPIO.output(10, False)
         GPIO.output(18, False)
         GPIO.output(26, False)
         GPIO.output(19, False)
         GPIO.output(11, False)
         time.sleep(speed)
         GPIO.output(12, True)
         GPIO.output(22, True)
         GPIO.output(23, True)
         GPIO.output(15, True)
         GPIO.output(7, True)
         time.sleep(speed)
         GPIO.output(12, False)
         GPIO.output(22, False)
         GPIO.output(23, False)
         GPIO.output(15, False)
         GPIO.output(7, False)
         time.sleep(speed)
         GPIO.output(16, True)
         GPIO.output(24, True)
         GPIO.output(21, True)
         GPIO.output(13, True)
         GPIO.output(5, True)
         time.sleep(speed)
         GPIO.output(16, False)
         GPIO.output(24, False)
         GPIO.output(21, False)
         GPIO.output(13, False)
         GPIO.output(5, False)
         time.sleep(speed)

def onebyone(no_of_times,speed):
    for i in range(0,no_of_times):
         print "\nLed Blink = " + str(i+1)
         GPIO.output(10, True)
         time.sleep(speed)
         GPIO.output(12, True)
         time.sleep(speed)
         GPIO.output(16, True)
         time.sleep(speed)
         GPIO.output(18, True)
         time.sleep(speed)
         GPIO.output(22, True)
         time.sleep(speed)
         GPIO.output(24, True)
         time.sleep(speed)
         GPIO.output(26, True)
         time.sleep(speed)
         GPIO.output(23, True)
         time.sleep(speed)
         GPIO.output(21, True)
         time.sleep(speed)
         GPIO.output(19, True)
         time.sleep(speed)
         GPIO.output(15, True)
         time.sleep(speed)
         GPIO.output(13, True)
         time.sleep(speed)
         GPIO.output(11, True)
         time.sleep(speed)
         GPIO.output(7, True)
         time.sleep(speed)
         GPIO.output(5, True)
         time.sleep(speed)
         GPIO.output(10, False)
         GPIO.output(12, False)
         GPIO.output(16, False)
         GPIO.output(18, False)
         GPIO.output(22, False)
         GPIO.output(24, False)
         GPIO.output(26, False)
         GPIO.output(23, False)
         GPIO.output(21, False)
         GPIO.output(19, False)
         GPIO.output(15, False)
         GPIO.output(13, False)
         GPIO.output(11, False)
         GPIO.output(7, False)
         GPIO.output(5, False)
         time.sleep(speed)
         GPIO.output(5, True)
         time.sleep(speed)
         GPIO.output(7, True)
         time.sleep(speed)
         GPIO.output(11, True)
         time.sleep(speed)
         GPIO.output(13, True)
         time.sleep(speed)
         GPIO.output(15, True)
         time.sleep(speed)
         GPIO.output(19, True)
         time.sleep(speed)
         GPIO.output(21, True)
         time.sleep(speed)
         GPIO.output(23, True)
         time.sleep(speed)
         GPIO.output(26, True)
         time.sleep(speed)
         GPIO.output(24, True)
         time.sleep(speed)
         GPIO.output(22, True)
         time.sleep(speed)
         GPIO.output(18, True)
         time.sleep(speed)
         GPIO.output(16, True)
         time.sleep(speed)
         GPIO.output(12, True)
         time.sleep(speed)
         GPIO.output(10, True)
         time.sleep(speed)
         GPIO.output(5, False)
         GPIO.output(7, False)
         GPIO.output(11, False)
         GPIO.output(13, False)
         GPIO.output(15, False)
         GPIO.output(19, False)
         GPIO.output(21, False)
         GPIO.output(23, False)
         GPIO.output(26, False)
         GPIO.output(24, False)
         GPIO.output(22, False)
         GPIO.output(18, False)
         GPIO.output(16, False)
         GPIO.output(12, False)
         GPIO.output(10, False)
         time.sleep(speed)
def running(no_of_times,speed):
    for i in range(0,no_of_times):
         print "\nLed Blink = " + str(i+1)
         GPIO.output(10, True)
         time.sleep(speed)
         GPIO.output(10, False)
         time.sleep(speed)
         GPIO.output(12, True)
         time.sleep(speed)
         GPIO.output(12, False)
         time.sleep(speed)
         GPIO.output(16, True)
         time.sleep(speed)
         GPIO.output(16, False)
         time.sleep(speed)
         GPIO.output(18, True)
         time.sleep(speed)
         GPIO.output(18, False)
         time.sleep(speed)
         GPIO.output(22, True)
         time.sleep(speed)
         GPIO.output(22, False)
         time.sleep(speed)
         GPIO.output(24, True)
         time.sleep(speed)
         GPIO.output(24, False)
         time.sleep(speed)
         GPIO.output(26, True)
         time.sleep(speed)
         GPIO.output(26, False)
         time.sleep(speed)
         GPIO.output(23, True)
         time.sleep(speed)
         GPIO.output(23, False)
         time.sleep(speed)
         GPIO.output(21, True)
         time.sleep(speed)
         GPIO.output(21, False)
         time.sleep(speed)
         GPIO.output(19, True)
         time.sleep(speed)
         GPIO.output(19, False)
         time.sleep(speed)
         GPIO.output(15, True)
         time.sleep(speed)
         GPIO.output(15, False)
         time.sleep(speed)
         GPIO.output(13, True)
         time.sleep(speed)
         GPIO.output(13, False)
         time.sleep(speed)
         GPIO.output(11, True)
         time.sleep(speed)
         GPIO.output(11, False)
         time.sleep(speed)
         GPIO.output(7, True)
         time.sleep(speed)
         GPIO.output(7, False)
         time.sleep(speed)
         GPIO.output(5, True)
         time.sleep(speed)
         GPIO.output(5, False)
         time.sleep(speed)
         GPIO.output(5, True)
         time.sleep(speed)
         GPIO.output(5, False)
         time.sleep(speed)
         GPIO.output(7, True)
         time.sleep(speed)
         GPIO.output(7, False)
         time.sleep(speed)
         GPIO.output(11, True)
         time.sleep(speed)
         GPIO.output(11, False)
         time.sleep(speed)
         GPIO.output(13, True)
         time.sleep(speed)
         GPIO.output(13, False)
         time.sleep(speed)
         GPIO.output(15, True)
         time.sleep(speed)
         GPIO.output(15, False)
         time.sleep(speed)
         GPIO.output(19, True)
         time.sleep(speed)
         GPIO.output(19, False)
         time.sleep(speed)
         GPIO.output(21, True)
         time.sleep(speed)
         GPIO.output(21, False)
         time.sleep(speed)
         GPIO.output(23, True)
         time.sleep(speed)
         GPIO.output(23, False)
         time.sleep(speed)
         GPIO.output(26, True)
         time.sleep(speed)
         GPIO.output(26, False)
         time.sleep(speed)
         GPIO.output(24, True)
         time.sleep(speed)
         GPIO.output(24, False)
         time.sleep(speed)
         GPIO.output(22, True)
         time.sleep(speed)
         GPIO.output(22, False)
         time.sleep(speed)
         GPIO.output(18, True)
         time.sleep(speed)
         GPIO.output(18, False)
         time.sleep(speed)
         GPIO.output(16, True)
         time.sleep(speed)
         GPIO.output(16, False)
         time.sleep(speed)
         GPIO.output(12, True)
         time.sleep(speed)
         GPIO.output(12, False)
         time.sleep(speed)
         GPIO.output(10, True)
         time.sleep(speed)
         GPIO.output(10, False)
         time.sleep(speed)
         
    print "\n\nThank You Sir ! Total number of times LED Blink = " +str(no_of_times) +"\n\n"
    GPIO.cleanup()
  
print "*** Welcome to LED Blinking Program ***"
print "____________________________________\n"
how_many = input("Enter the total number of times to blink LED = ")
speed = input("\nEnter the blink duration in seconds = ")
onebyone(int(how_many),float(speed))
rgb(int(how_many),float(speed))
running(int(how_many),float(speed))
